export const ZIP_HREF = "/downloads/helios-lakehouse-dab.zip";
export const ZIP_NAME = "helios-lakehouse-dab.zip";

export type FileLang = "yaml" | "python" | "toml" | "bash" | "md" | "text" | "gitignore";

export type BundleFile = {
  path: string;
  lang: FileLang;
  category: "root" | "cicd" | "resources" | "src" | "tests" | "scripts";
  summary: string;
};

export const BUNDLE_FILES: BundleFile[] = [
  { path: "README.md", lang: "md", category: "root", summary: "How the one-repo lakehouse is structured and deployed" },
  { path: "databricks.yml", lang: "yaml", category: "root", summary: "Bundle entry: targets, variables, permissions, artifacts" },
  { path: "pyproject.toml", lang: "toml", category: "root", summary: "Python package, wheel build, lint and test extras" },
  { path: "Makefile", lang: "text", category: "root", summary: "validate / deploy / test shortcuts" },
  { path: ".gitignore", lang: "gitignore", category: "root", summary: "Venv, dist, secrets, Databricks local state" },
  { path: ".pre-commit-config.yaml", lang: "yaml", category: "root", summary: "Ruff, yamlfmt, trailing whitespace" },
  { path: "CODEOWNERS", lang: "text", category: "root", summary: "Platform vs domain ownership" },
  { path: "CONTRIBUTING.md", lang: "md", category: "root", summary: "PR path, target promotion, run_as rules" },
  { path: ".env.example", lang: "text", category: "root", summary: "Local CLI host placeholders — no secrets" },
  { path: ".github/workflows/ci-validate.yml", lang: "yaml", category: "cicd", summary: "PR: lint, unit tests, bundle validate" },
  { path: ".github/workflows/deploy-dev.yml", lang: "yaml", category: "cicd", summary: "Push to develop → deploy + smoke run" },
  { path: ".github/workflows/deploy-staging.yml", lang: "yaml", category: "cicd", summary: "Merge to staging → deploy and integration job" },
  { path: ".github/workflows/deploy-prod.yml", lang: "yaml", category: "cicd", summary: "Main + environment approval → production" },
  { path: ".github/PULL_REQUEST_TEMPLATE.md", lang: "md", category: "cicd", summary: "Impact checklist for jobs / pipelines / ML" },
  { path: "azure-pipelines.yml", lang: "yaml", category: "cicd", summary: "Azure DevOps equivalent of the GitHub path" },
  { path: "resources/unity/schemas.yml", lang: "yaml", category: "resources", summary: "Bronze / silver / gold / ml Unity Catalog schemas" },
  { path: "resources/unity/volumes.yml", lang: "yaml", category: "resources", summary: "Landing and feature volumes" },
  { path: "resources/pipelines/bronze_ingest.pipeline.yml", lang: "yaml", category: "resources", summary: "Autoloader bronze Lakeflow pipeline" },
  { path: "resources/pipelines/silver_conform.pipeline.yml", lang: "yaml", category: "resources", summary: "SCD2 + conformed silver pipeline" },
  { path: "resources/pipelines/gold_marts.pipeline.yml", lang: "yaml", category: "resources", summary: "Daily sales, customer 360, store marts" },
  { path: "resources/jobs/medallion_orchestrator.job.yml", lang: "yaml", category: "resources", summary: "Nightly bronze → silver → gold DAG" },
  { path: "resources/jobs/file_arrival_ingest.job.yml", lang: "yaml", category: "resources", summary: "File-arrival trigger for POS drops" },
  { path: "resources/jobs/feature_engineering.job.yml", lang: "yaml", category: "resources", summary: "Demand feature table refresh" },
  { path: "resources/jobs/model_training.job.yml", lang: "yaml", category: "resources", summary: "Train, evaluate, register LightGBM demand model" },
  { path: "resources/jobs/batch_inference.job.yml", lang: "yaml", category: "resources", summary: "Weekly store-SKU forecast scoring" },
  { path: "resources/jobs/model_monitoring.job.yml", lang: "yaml", category: "resources", summary: "Drift check that can trigger retrain" },
  { path: "resources/ml/experiment.yml", lang: "yaml", category: "resources", summary: "MLflow experiment for demand forecast" },
  { path: "resources/ml/registered_model.yml", lang: "yaml", category: "resources", summary: "Unity Catalog registered model + grants" },
  { path: "resources/ml/serving_endpoint.yml", lang: "yaml", category: "resources", summary: "Model serving endpoint (prod only)" },
  { path: "resources/quality/monitors.yml", lang: "yaml", category: "resources", summary: "Lakehouse monitors on gold + inference" },
  { path: "src/helios_lakehouse/__init__.py", lang: "python", category: "src", summary: "Package version" },
  { path: "src/helios_lakehouse/common/config.py", lang: "python", category: "src", summary: "Catalog / volume / table path helpers" },
  { path: "src/helios_lakehouse/common/transforms.py", lang: "python", category: "src", summary: "Pure functions used by pipelines and tests" },
  { path: "src/helios_lakehouse/common/expectations.py", lang: "python", category: "src", summary: "Reusable data-quality predicates" },
  { path: "src/helios_lakehouse/bronze/pos_transactions.py", lang: "python", category: "src", summary: "POS Autoloader streaming table" },
  { path: "src/helios_lakehouse/bronze/ecommerce_events.py", lang: "python", category: "src", summary: "Clickstream Autoloader table" },
  { path: "src/helios_lakehouse/bronze/inventory_snapshots.py", lang: "python", category: "src", summary: "Hourly on-hand snapshots" },
  { path: "src/helios_lakehouse/bronze/customer_profiles.py", lang: "python", category: "src", summary: "CRM customer extract" },
  { path: "src/helios_lakehouse/silver/transactions_conformed.py", lang: "python", category: "src", summary: "Unified POS + ecom transactions" },
  { path: "src/helios_lakehouse/silver/customers_scd2.py", lang: "python", category: "src", summary: "Customer SCD2 dimension" },
  { path: "src/helios_lakehouse/gold/sales_daily.py", lang: "python", category: "src", summary: "Store-SKU daily sales mart" },
  { path: "src/helios_lakehouse/gold/customer_360.py", lang: "python", category: "src", summary: "Customer 360 gold table" },
  { path: "src/helios_lakehouse/features/demand_features.py", lang: "python", category: "src", summary: "Feature table for demand model" },
  { path: "src/helios_lakehouse/ml/train_demand.py", lang: "python", category: "src", summary: "Training entrypoint with MLflow" },
  { path: "src/helios_lakehouse/ml/evaluate.py", lang: "python", category: "src", summary: "Holdout metrics and promotion gate" },
  { path: "src/helios_lakehouse/ml/register.py", lang: "python", category: "src", summary: "UC model registration + alias" },
  { path: "src/helios_lakehouse/ml/infer_batch.py", lang: "python", category: "src", summary: "Batch scoring writer" },
  { path: "tests/conftest.py", lang: "python", category: "tests", summary: "Shared fixtures" },
  { path: "tests/unit/test_transforms.py", lang: "python", category: "tests", summary: "SKU, amount, week_id unit tests" },
  { path: "tests/unit/test_features.py", lang: "python", category: "tests", summary: "Recency / demand label tests" },
  { path: "tests/unit/test_config.py", lang: "python", category: "tests", summary: "Path helper tests" },
  { path: "scripts/validate.sh", lang: "bash", category: "scripts", summary: "Local lint + bundle validate" },
  { path: "scripts/deploy.sh", lang: "bash", category: "scripts", summary: "Target-aware deploy wrapper" },
];

export const RESOURCES = [
  {
    id: "bronze",
    kind: "Pipeline",
    name: "bronze_ingest",
    layer: "Bronze",
    file: "resources/pipelines/bronze_ingest.pipeline.yml",
    blurb: "Autoloader from the landing volume. Four streaming tables, schema evolution, CDF on.",
  },
  {
    id: "silver",
    kind: "Pipeline",
    name: "silver_conform",
    layer: "Silver",
    file: "resources/pipelines/silver_conform.pipeline.yml",
    blurb: "Conformed transactions, product master, customer SCD2. Expectations drop poison rows.",
  },
  {
    id: "gold",
    kind: "Pipeline",
    name: "gold_marts",
    layer: "Gold",
    file: "resources/pipelines/gold_marts.pipeline.yml",
    blurb: "Daily sales, customer 360, store performance. Served to BI and features.",
  },
  {
    id: "orch",
    kind: "Job",
    name: "medallion_orchestrator",
    layer: "Orchestration",
    file: "resources/jobs/medallion_orchestrator.job.yml",
    blurb: "02:15 America/New_York. Refreshes bronze → silver → gold, then kicks features.",
  },
  {
    id: "arrival",
    kind: "Job",
    name: "file_arrival_ingest",
    layer: "Ingest",
    file: "resources/jobs/file_arrival_ingest.job.yml",
    blurb: "File-arrival trigger on POS drops. Debounced 60s after last write.",
  },
  {
    id: "feat",
    kind: "Job",
    name: "feature_engineering",
    layer: "ML",
    file: "resources/jobs/feature_engineering.job.yml",
    blurb: "Point-in-time demand features written to the ml schema.",
  },
  {
    id: "train",
    kind: "Job",
    name: "model_training",
    layer: "ML",
    file: "resources/jobs/model_training.job.yml",
    blurb: "Train LightGBM, evaluate, register only if WAPE gate passes.",
  },
  {
    id: "score",
    kind: "Job",
    name: "batch_inference",
    layer: "ML",
    file: "resources/jobs/batch_inference.job.yml",
    blurb: "Scores next-12-week demand for every in-range store-SKU.",
  },
  {
    id: "mon",
    kind: "Job",
    name: "model_monitoring",
    layer: "MLOps",
    file: "resources/jobs/model_monitoring.job.yml",
    blurb: "Daily WAPE check. Condition task retrains on sustained drift.",
  },
  {
    id: "exp",
    kind: "Experiment",
    name: "demand_forecast",
    layer: "ML",
    file: "resources/ml/experiment.yml",
    blurb: "MLflow experiment path, one per target.",
  },
  {
    id: "model",
    kind: "Registered model",
    name: "demand_forecast",
    layer: "ML",
    file: "resources/ml/registered_model.yml",
    blurb: "Unity Catalog model with Champion / Challenger aliases.",
  },
  {
    id: "serve",
    kind: "Serving",
    name: "helios-demand",
    layer: "ML",
    file: "resources/ml/serving_endpoint.yml",
    blurb: "Serverless endpoint, scale-to-zero, prod target only.",
  },
] as const;

export const TARGETS = [
  {
    id: "dev",
    mode: "development",
    catalog: "helios_dev",
    host: "adb-dev-helios.azuredatabricks.net",
    runAs: "the deploying user",
    schedules: "Paused",
    prefix: "[dev <user>] ",
    note: "Personal copies. Full refresh allowed. No shared blast radius.",
  },
  {
    id: "staging",
    mode: "production",
    catalog: "helios_staging",
    host: "adb-staging-helios.azuredatabricks.net",
    runAs: "staging service principal",
    schedules: "Running",
    prefix: "none",
    note: "Shared workspace. Integration tests and Champion promotion happen here.",
  },
  {
    id: "prod",
    mode: "production",
    catalog: "helios_prod",
    host: "adb-prod-helios.azuredatabricks.net",
    runAs: "prod service principal",
    schedules: "Running",
    prefix: "none",
    note: "Git-locked to main. Environment reviewers required before deploy.",
  },
] as const;

export const PIPELINE_STEPS = [
  {
    id: "pr",
    title: "Pull request",
    env: "dev",
    actions: ["ruff", "pytest -q tests/unit", "databricks bundle validate -t dev"],
  },
  {
    id: "dev",
    title: "Merge to develop",
    env: "dev",
    actions: ["bundle deploy -t dev", "bundle run medallion_orchestrator --refresh"],
  },
  {
    id: "stg",
    title: "Merge to staging",
    env: "staging",
    actions: ["bundle deploy -t staging", "run model_training (Challenger)", "quality monitor refresh"],
  },
  {
    id: "prod",
    title: "Release to main",
    env: "prod",
    actions: ["environment approval", "bundle deploy -t prod", "no automatic full refresh"],
  },
] as const;
