/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CicdRouteImport } from './routes/cicd'
import { Route as FilesRouteImport } from './routes/files'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScoreRouteImport } from './routes/score'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CicdRoute = CicdRouteImport.update({
  id: '/cicd',
  path: '/cicd',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cicd': typeof CicdRoute
  '/files': typeof FilesRoute
  '/guide': typeof GuideRoute
  '/resources': typeof ResourcesRoute
  '/score': typeof ScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cicd': typeof CicdRoute
  '/files': typeof FilesRoute
  '/guide': typeof GuideRoute
  '/resources': typeof ResourcesRoute
  '/score': typeof ScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cicd': typeof CicdRoute
  '/files': typeof FilesRoute
  '/guide': typeof GuideRoute
  '/resources': typeof ResourcesRoute
  '/score': typeof ScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cicd' | '/files' | '/guide' | '/resources' | '/score'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cicd' | '/files' | '/guide' | '/resources' | '/score'
  id: '__root__' | '/' | '/cicd' | '/files' | '/guide' | '/resources' | '/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CicdRoute: typeof CicdRoute
  FilesRoute: typeof FilesRoute
  GuideRoute: typeof GuideRoute
  ResourcesRoute: typeof ResourcesRoute
  ScoreRoute: typeof ScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cicd': {
      id: '/cicd'
      path: '/cicd'
      fullPath: '/cicd'
      preLoaderRoute: typeof CicdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CicdRoute: CicdRoute,
  FilesRoute: FilesRoute,
  GuideRoute: GuideRoute,
  ResourcesRoute: ResourcesRoute,
  ScoreRoute: ScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
